version: "3.3"

networks:
  monitor-network:
    driver: bridge

volumes:
  prometheus-volume:
    driver: local
  grafana-volume:
    driver: local
  testnet-volume:
    driver: local

services:

  htmlcoin-testnet:
    image: htmlcoin/htmlcoin:latest
    container_name: htmlcoin-testnet
    restart: always
    ports:
      - "4889:4889"
    command: htmlcoind -testnet -txindex -addrindex=1 -rpcbind=0.0.0.0:4889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=htmlcoin -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
    networks:
      - monitor-network
    volumes:
      - testnet-volume:/root/.htmlcoin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - monitor-network
    depends_on:
      - htmlcoin-testnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    user: root
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - monitor-network
    depends_on:
      - htmlcoin-testnet
      - prometheus

  htmlcoin-exporter:
    image: meherett/htmlcoin-exporter:latest
    container_name: htmlcoin-exporter
    ports:
      - "6363:6363"
    restart: always
    environment:
      HTMLCOIN_RPC_HOST: "htmlcoin-testnet"
      HTMLCOIN_RPC_PORT: "4889"
      REFRESH_SECONDS: 5
      LOG_LEVEL: "INFO"
      TIMEOUT: 15
    networks:
      - monitor-network
    depends_on:
      - htmlcoin-testnet
      - prometheus
      - grafana
