global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "qtum-exporter"
    static_configs:
      - targets: ["qtum-exporter:6363"]
