{
 "title": "Htmlcoin",
 "tags": [ "Htmlcoin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(rate(htmlcoin_blocks[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(htmlcoin_blocks[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(htmlcoin_blocks[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(htmlcoin_blocks[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(htmlcoin_difficulty)", "legendFormat": "difficulty" }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(htmlcoin_hash_ps)", "legendFormat": "120-blocks" },
    { "expr": "avg(htmlcoin_hash_ps_neg1)", "legendFormat": "last-difficulty" }
   ]
  },
  {
   "title": "Block value",
   "type": "graph",
   "description": "Value of the block transactions in HTMLCOIN.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(htmlcoin_latest_block_value)",
     "legendFormat": "HTMLCOIN"
    }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(htmlcoin_num_chain_tips)", "legendFormat": "tips" }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(htmlcoin_total_bytes_sent[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(htmlcoin_total_bytes_recv[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "graph",
   "description": "The Htmlcoin protocol and server versions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "protocol version" }
   ],
   "targets": [
    { "expr": "avg(htmlcoin_protocol_version)", "legendFormat": "protocol" },
    { "expr": "avg(htmlcoin_server_version)", "legendFormat": "server" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(htmlcoin_banned_until) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    { "expr": "sum(htmlcoin_connections)", "legendFormat": "peers" }
   ]
  },
  {
   "title": "Estimated Fee",
   "type": "graph",
   "description": "The estimated smart fee for confirmation of transactions in a given number of blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(htmlcoin_estimate_smart_fee_2)",
     "legendFormat": "2-blocks"
    },
    {
     "expr": "avg(htmlcoin_estimate_smart_fee_20)",
     "legendFormat": "20-blocks"
    },
    {
     "expr": "avg(htmlcoin_estimate_smart_fee_3)",
     "legendFormat": "3-blocks"
    },
    {
     "expr": "avg(htmlcoin_estimate_smart_fee_5)",
     "legendFormat": "5-blocks"
    }
   ]
  }
 ]
}